-- NOTE: This file is auto generated by ./sql-generator

-- BurstRepository.streamForBurstDetection
select
  "asset"."id" as "id",
  "asset"."ownerId" as "ownerId",
  "asset"."originalFileName" as "originalFileName",
  "asset_exif"."dateTimeOriginal" as "dateTimeOriginal",
  "asset_exif"."make" as "make",
  "asset_exif"."model" as "model"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."type" = $1
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and "asset_exif"."dateTimeOriginal" is not null
  and "asset"."visibility" in ('archive', 'timeline')
order by
  "ownerId",
  "make",
  "model",
  "dateTimeOriginal",
  "id"

-- BurstRepository.getEmbeddingDistances
select
  "smart_search"."assetId" as "assetId",
  smart_search.embedding <=> (
    select
      "reference"."embedding"
    from
      "smart_search" as "reference"
    where
      "reference"."assetId" = $1::uuid
  ) as "distance"
from
  "smart_search"
where
  "smart_search"."assetId" = any ($2::uuid[])

-- BurstRepository.getStackableMembers
select
  "burst_group_asset"."assetId" as "assetId",
  "burst_group_asset"."distance" as "distance"
from
  "burst_group_asset"
  inner join "asset" on "asset"."id" = "burst_group_asset"."assetId"
where
  "burst_group_asset"."burstGroupId" = $1::uuid
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and "asset"."visibility" in ('archive', 'timeline')
order by
  "distance"

-- BurstRepository.getGroupedAssetNames
select
  "asset"."id" as "id",
  "asset"."originalFileName" as "originalFileName",
  "asset_exif"."dateTimeOriginal" as "dateTimeOriginal",
  "asset_exif"."make" as "make",
  "asset_exif"."model" as "model"
from
  "burst_group_asset"
  inner join "burst_group" on "burst_group"."id" = "burst_group_asset"."burstGroupId"
  inner join "asset" on "asset"."id" = "burst_group_asset"."assetId"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "burst_group"."ownerId" = $1::uuid

-- BurstRepository.getUnstackedInRange
select
  "asset"."id" as "id",
  "asset"."originalFileName" as "originalFileName"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1::uuid
  and "asset"."type" = $2
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and "asset_exif"."dateTimeOriginal" >= $3
  and "asset_exif"."dateTimeOriginal" <= $4
  and "asset"."visibility" in ('archive', 'timeline')

-- BurstRepository.getAllForUser
select
  "burst_group".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "burst_group_asset"."assetId" as "assetId",
          "burst_group_asset"."distance" as "distance"
        from
          "burst_group_asset"
        where
          "burst_group_asset"."burstGroupId" = "burst_group"."id"
        order by
          "burst_group_asset"."distance"
      ) as agg
  ) as "members"
from
  "burst_group"
where
  "burst_group"."ownerId" = $1::uuid
  and "burst_group"."status" = $2
order by
  "burst_group"."createdAt" desc

-- BurstRepository.getById
select
  "burst_group".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "burst_group_asset"."assetId" as "assetId",
          "burst_group_asset"."distance" as "distance"
        from
          "burst_group_asset"
        where
          "burst_group_asset"."burstGroupId" = "burst_group"."id"
        order by
          "burst_group_asset"."distance"
      ) as agg
  ) as "members"
from
  "burst_group"
where
  "burst_group"."id" = $1::uuid
